name: Auto commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: "01 00,12 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG
        run: echo "::debug::Ref = ${{github.ref}}"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=$(date '+%Y-%m-%dT%H:%M:%SZ')
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "muammarm28@gmail.com"
          git config --local user.name "faprikaa"
          git add -A
          rand=$[$RANDOM % 10]
          commit_message="chore(bot): Auto Commit - $d"
          git commit -m "$commit_message"

      - name: Push changes
        run: git push origin ${{ github.ref }}

  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
