name: Commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: "01,01 00,12 * * *"
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    timeout-minutes: 8000
    env:
      RANDOM_SLEEP : $(( ( RANDOM % 432000 ) + 1 ))
    steps:
      - name: DEBUG
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%d %H:%M:%S'`
          echo $d > LAST_UPDATED
          
      - name: Random Sleep
        run: |
          # Generate a random number between 1 and 259200
          echo "Sleeping for ${{env.RANDOM_SLEEP}} seconds..."
          sleep $random_sleep
          
      - name: Commit changes
        run: |
          git config --local user.email "muammarm28@gmail.com"
          git config --local user.name "faprikaa"
          git add -A
          d=`date '+%Y-%m-%d %H:%M:%S'`
          git commit -m "Commit - $d"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          

